# Generated by Django 4.1 on 2022-08-06 10:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='events/%Y/%m/%d/')),
                ('description', tinymce.models.HTMLField()),
                ('added_by', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('address_street', models.CharField(max_length=300)),
                ('address_suburb', models.CharField(blank=True, max_length=300, null=True)),
                ('address_town', models.CharField(blank=True, max_length=300, null=True)),
                ('address_postal_code', models.CharField(max_length=5)),
            ],
        ),
    ]
