# Generated by Django 4.1 on 2022-08-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address_postal_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='address_street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='address_suburb',
            new_name='suburb',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='address_town',
            new_name='town',
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
