# Generated by Django 4.1 on 2022-08-06 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_address_postal_code_event_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Date and time the event will start'),
        ),
    ]
