# Generated by Django 4.1 on 2022-08-06 06:48

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='news/%Y/%m/%d/')),
                ('excerpt', tinymce.models.HTMLField(blank=True, null=True)),
                ('body', tinymce.models.HTMLField()),
                ('author', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
