# Generated by Django 4.1 on 2022-08-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0002_alter_cause_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='excerpt',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
