# Generated by Django 4.1 on 2022-08-06 06:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0003_alter_cause_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='excerpt',
            field=tinymce.models.HTMLField(blank=True, help_text='Excerpt is made from the first paragraph of content', null=True),
        ),
    ]
