# Generated by Django 4.1 on 2022-08-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0004_alter_cause_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
